/**
 * Walks the `skill/` directory and emits `src/generated/assets.ts`, a single
 * TypeScript file that exports every file's contents base64-encoded. The
 * watcher's `init` command later writes these out to the user's local skills
 * directory.
 *
 * Skips: node_modules/, dotfiles. Files are recorded with their relative
 * path from `skill/`.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SKILL_ROOT = path.join(__dirname, "skill");
const ASSETS_OUTPUT = path.join(__dirname, "src/generated/assets.ts");
const BUILD_INFO_OUTPUT = path.join(__dirname, "src/generated/build-info.ts");

interface Entry {
  relPath: string;
  base64: string;
}

async function walk(dir: string, relBase = ""): Promise<Entry[]> {
  const entries: Entry[] = [];
  const items = await fs.readdir(dir, { withFileTypes: true });
  for (const item of items) {
    if (item.name.startsWith(".") || item.name === "node_modules") continue;
    const abs = path.join(dir, item.name);
    const rel = relBase ? `${relBase}/${item.name}` : item.name;
    if (item.isDirectory()) {
      entries.push(...(await walk(abs, rel)));
    } else if (item.isFile()) {
      const buf = await fs.readFile(abs);
      entries.push({ relPath: rel, base64: buf.toString("base64") });
    }
  }
  return entries;
}

async function main() {
  const files = await walk(SKILL_ROOT);
  files.sort((a, b) => a.relPath.localeCompare(b.relPath));

  const body = files
    .map((f) => `  ${JSON.stringify(f.relPath)}: ${JSON.stringify(f.base64)},`)
    .join("\n");

  const out = `// AUTOGENERATED by build-assets.ts. Do not edit by hand.
export const SKILL_ASSETS: Record<string, string> = {
${body}
};
`;

  await fs.mkdir(path.dirname(ASSETS_OUTPUT), { recursive: true });
  await fs.writeFile(ASSETS_OUTPUT, out);
  console.log(
    `Wrote ${files.length} files (${formatBytes(out.length)}) to ${path.relative(process.cwd(), ASSETS_OUTPUT)}`,
  );

  // Bake the Supabase URL in. Read from NEXT_PUBLIC_SUPABASE_URL (Vercel
  // convention) with a fallback to SUPABASE_URL. The runtime can still
  // override via MYSELF_SUPABASE_URL but no override should be needed.
  const supabaseUrl =
    process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "";
  const buildInfo = `// AUTOGENERATED by build-assets.ts. Do not edit by hand.
export const BAKED_SUPABASE_URL = ${JSON.stringify(supabaseUrl)};
export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};
`;
  await fs.writeFile(BUILD_INFO_OUTPUT, buildInfo);
  if (!supabaseUrl) {
    console.warn(
      "WARNING: NEXT_PUBLIC_SUPABASE_URL not set; the built watcher will require MYSELF_SUPABASE_URL at runtime.",
    );
  } else {
    console.log(`Baked Supabase URL: ${supabaseUrl}`);
  }
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(2)} MB`;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
