import { NextRequest, NextResponse } from "next/server";
import { nanoid } from "nanoid";

import { bootApp } from "@/lib/core/init";
import { requireUserId } from "@/lib/core/route-helpers";
import {
  executeCommand,
  isSSHConnected,
  getDefaultConnection,
} from "@/lib/modules/claw/actions";
import { tokeniseAgentOutput } from "@/lib/claw-ai/parser";
import type {
  ClawUIMessage,
  ClawDataParts,
} from "@/lib/claw-ai/parts";

interface HistoryMessage {
  role: "user" | "agent";
  content: string;
  timestamp: number;
}

/**
 * OpenClaw stores conversation transcripts as JSONL files at:
 *   ~/.openclaw/agents/<agentId>/sessions/<sessionKey>.jsonl
 *
 * Each line is a JSON object. Message entries have:
 *   { "type": "message", "timestamp": "...", "message": { "role": "user"|"assistant", "content": [...] } }
 *
 * content is an array of blocks — we extract text from { "type": "text", "text": "..." } blocks.
 */
function extractTextFromContent(content: unknown): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  const texts: string[] = [];
  for (const block of content) {
    if (block && typeof block === "object") {
      const b = block as Record<string, unknown>;
      if (b.type === "text" && typeof b.text === "string") {
        texts.push(b.text);
      }
    }
  }
  return texts.join("\n");
}

/**
 * Map a historical assistant message text into AI SDK message parts:
 * any embedded `[CARD]`/`[TOOL_CALL]`/`[UI_SPEC]` blocks become typed
 * `data-*` parts, and free text becomes a `text` part. This lets a
 * resumed session re-hydrate generative cards exactly like a live
 * stream does.
 */
function assistantPartsFromText(text: string): ClawUIMessage["parts"] {
  const fragments = tokeniseAgentOutput(text);
  const parts: ClawUIMessage["parts"] = [];

  for (const fragment of fragments) {
    if (fragment.kind === "text") {
      parts.push({ type: "text", text: fragment.text });
      continue;
    }
    // The fragment.type is one of the keys in ClawDataParts. The
    // resulting part shape is `{ type: 'data-<name>', id, data }`,
    // which matches the schema generated by `UIMessage<ClawDataParts>`.
    const dataPart = {
      type: `data-${fragment.type}` as `data-${keyof ClawDataParts}`,
      id: fragment.id,
      data: fragment.data,
    };
    parts.push(dataPart as unknown as ClawUIMessage["parts"][number]);
  }

  if (parts.length === 0) {
    parts.push({ type: "text", text });
  }

  return parts;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  bootApp();
  const auth = await requireUserId();
  if ("response" in auth) return auth.response;
  try {
    const { id: sessionKey } = await params;
    const cid = req.nextUrl.searchParams.get("connectionId");
    const agentId = req.nextUrl.searchParams.get("agentId");
    const connectionId = cid ?? (await getDefaultConnection(auth.userId))?.id;

    if (!connectionId) {
      return NextResponse.json({ error: "No connection configured" }, { status: 400 });
    }
    if (!isSSHConnected(connectionId)) {
      return NextResponse.json({ error: "Not connected via SSH" }, { status: 400 });
    }
    if (!agentId) {
      return NextResponse.json({ error: "agentId is required" }, { status: 400 });
    }

    const safeAgent = agentId.replace(/['"\\$`!]/g, "");
    const safeKey = sessionKey.replace(/['"\\$`!]/g, "");

    // OpenClaw sessions have a compound `key` (e.g. "agent:main:cron:UUID:run:UUID")
    // and a separate `sessionId` UUID that names the transcript file on disk.
    const transcriptId = req.nextUrl.searchParams.get("transcriptId");
    const fileId = transcriptId
      ? transcriptId.replace(/['"\\$`!]/g, "")
      : safeKey.includes(":") ? safeKey.split(":").pop()! : safeKey;

    // Per OpenClaw docs, transcripts live at:
    //   ~/.openclaw/agents/<agentId>/sessions/<sessionId>.jsonl
    // Tilde must NOT be quoted so bash expands it inside `bash -lc '...'`.
    const transcriptPath = `~/.openclaw/agents/${safeAgent}/sessions/${fileId}.jsonl`;
    const catRes = await executeCommand(
      connectionId,
      `cat ${transcriptPath} 2>/dev/null || echo ""`,
      60000,
    );

    const messages: HistoryMessage[] = [];
    const raw = catRes.stdout || "";

    if (raw.trim()) {
      const lines = raw.split("\n").filter((l) => l.trim());
      for (const line of lines) {
        try {
          const entry = JSON.parse(line) as Record<string, unknown>;

          if (entry.type !== undefined && entry.type !== "message") continue;

          const msg = entry.message as Record<string, unknown> | undefined;
          if (!msg) continue;

          const role = msg.role as string;
          if (role !== "user" && role !== "assistant") continue;

          const text = extractTextFromContent(msg.content);
          if (!text.trim()) continue;

          let timestamp: number;
          if (typeof entry.timestamp === "string") {
            timestamp = new Date(entry.timestamp).getTime();
          } else if (typeof entry.timestamp === "number") {
            timestamp = entry.timestamp;
          } else {
            timestamp = Date.now();
          }

          messages.push({
            role: role === "user" ? "user" : "agent",
            content: text,
            timestamp,
          });
        } catch {
          // skip malformed lines
        }
      }
    }

    // Convert to AI SDK UIMessage shape so `useChat({ messages: ... })`
    // can hydrate the conversation directly. User messages stay plain
    // text; assistant messages are tokenised so embedded cards re-render.
    const uiMessages: ClawUIMessage[] = messages.map((m) => ({
      id: nanoid(),
      role: m.role === "user" ? "user" : "assistant",
      parts:
        m.role === "user"
          ? [{ type: "text", text: m.content }]
          : assistantPartsFromText(m.content),
      metadata: { sessionId: sessionKey, agentId },
    }));

    return NextResponse.json({ messages, uiMessages });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Unknown error" },
      { status: 500 },
    );
  }
}
